apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: kudo-ci@prow.kudo.dev
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
    - dns01:
        clouddns:
          project: maestro-229419
          serviceAccountSecretRef:
            name: gcp-service-account
            key: service-account.json
